on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          api_key: ${{ secrets.api_key }}              # Azure API key
          api_type: "azure"                            # API type, set as a literal string
          api_version: "2023-05-15"      # Azure API version
          api_base: ${{ secrets.api_base }}            # Azure API base URL
          openai_deployment_id: ${{ secrets.openai_deployment_id }} # OpenAI deployment ID
          model: ${{ secrets.model }}   
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_review: "true" # enable\disable auto review
          github_action.auto_describe: "true" # enable\disable auto describe
          github_action.auto_improve: "true" # enable\disable auto improve